#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

mkdir -p dist/artifacts
cp bin/cloudweav-network-controller dist/artifacts/cloudweav-network-controller${SUFFIX}
cp bin/cloudweav-network-helper dist/artifacts/cloudweav-network-helper${SUFFIX}
cp bin/cloudweav-network-webhook dist/artifacts/cloudweav-network-webhook${SUFFIX}

CONTROLLER_IMAGE=${REPO}/cloudweav-network-controller:${TAG}
HELPER_IMAGE=${REPO}/cloudweav-network-helper:${TAG}
WEBHOOK_IMAGE=${REPO}/cloudweav-network-webhook:${TAG}
DOCKERFILE_CONTROLLER=package/Dockerfile
DOCKERFILE_HELPER=package/Dockerfile.helper
DOCKERFILE_WEBHOOK=package/Dockerfile.webhook
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE_CONTROLLER} -t ${CONTROLLER_IMAGE} .
echo Built ${CONTROLLER_IMAGE}

docker build -f ${DOCKERFILE_HELPER} -t ${HELPER_IMAGE} .
echo Built ${HELPER_IMAGE}

docker build -f ${DOCKERFILE_WEBHOOK} -t ${WEBHOOK_IMAGE} .
echo Built ${WEBHOOK_IMAGE}
